[package]
name = "rtlola_kotlin_bridge"
version = "0.2.0"
authors = ["Yannik Schnitzer <s8yaschn@stud.uni-saarland.de>, Maximilian Schwenger <maximilian.schwenger@cispa.de>"]
edition = "2018"
license = "MIT"
description = "Provides a simple bridge to use the RTLola-Interpreter in Kotlin."
homepage = "https://rtlola.org"
repository = "https://github.com/reactive-systems/RTLola-Kotlin-Bridge"
readme = "README.md"
keywords = ["bridge", "rtlola", "kotlin", "monitoring"]
categories = ["development-tools::ffi", "api-bindings"]

[dependencies]
jni = { version = "0.19.0", default-features = false }
rtlola-interpreter = "0.7.0"
rtlola-frontend = "0.5.0"
ordered-float = "2.5.1"
byteorder = "1.3.2"

[profile.release]
lto = true

[lib]
name = "rtlola_kotlin_bridge"
crate-type = ["cdylib"]
